version: '2.1'

services:
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./tmp/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: logstash:alpine
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./docker/elk/logstash/config:/etc/logstash/conf.d
      - ./log:/log
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana
    volumes:
      - ./docker/elk/kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
